# Generated by Django 4.2.10 on 2024-03-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMetaData',
            fields=[
                ('question_meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_meta_text', models.TextField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_meta_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.questionmetadata'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.test'),
        ),
    ]
