# Generated by Django 4.2.10 on 2024-03-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_questionmetadata_test_question_format_question_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='questionmetadata',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
