# Generated by Django 4.2.10 on 2024-03-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_question_test_remove_questionmetadata_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('test_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateField()),
                ('score', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
