# Generated by Django 4.2.11 on 2024-04-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('finished_ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_answer', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.question')),
                ('test_history_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.testhistory')),
            ],
        ),
    ]
