# Generated by Django 4.2.11 on 2024-04-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_usertestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='skill_name',
            field=models.IntegerField(default=0),
        ),
    ]
