# Generated by Django 4.2.11 on 2024-04-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_testhistory_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='format_name',
            field=models.JSONField(null=True),
        ),
    ]
