# Generated by Django 4.2.11 on 2024-04-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_testhistory_format_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
