# Generated by Django 4.2.11 on 2024-04-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_testhistory_format_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testhistory',
            name='score',
        ),
        migrations.AddField(
            model_name='testhistory',
            name='total_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
