# Generated by Django 4.2.11 on 2024-04-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_testhistory_score_testhistory_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='test_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='total_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testhistory',
            name='user_score',
            field=models.IntegerField(),
        ),
    ]
