# Generated by Django 4.2.11 on 2024-04-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='writing_answer',
            field=models.TextField(null=True),
        ),
    ]
