# Generated by Django 4.2.11 on 2024-04-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_question_writing_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
