# Generated by Django 4.2.11 on 2024-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_usertestresult_user_writing_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresult',
            name='user_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='user_writing_answer',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
