# Generated by Django 4.2.11 on 2024-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_flashcardset_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='suggested_writing_answer',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
